"""initial schema

Revision ID: 50445f5a9e59
Revises:
Create Date: 2026-09-14 18:22:40.308429

Hand-written rather than autogenerated: Phase 0 has no live PostgreSQL
instance available to diff against (see DEVELOPMENT.md). Columns/types here
must be kept in sync with `ibi.db.models` by hand until a real database is
available for `alembic revision --autogenerate` to verify against — at
which point this note can be removed.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Renders as JSONB on PostgreSQL (indexable, binary storage), plain JSON on
# every other dialect. Must match ibi.db.base.portable_json().
_JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

revision: str = '50445f5a9e59'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "entities",
        sa.Column("entity_id", sa.String(64), primary_key=True),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("canonical_name", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "source_documents",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("source", sa.String(255), nullable=False),
        sa.Column("source_tier", sa.String(32), nullable=False),
        sa.Column("source_url", sa.String(2048), nullable=True),
        sa.Column("content_ref", sa.String(2048), nullable=True),
        sa.Column("publication_date", sa.Date, nullable=True),
        sa.Column("retrieval_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "observations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column(
            "source_document_id", sa.Integer, sa.ForeignKey("source_documents.id"), nullable=True
        ),
        sa.Column("key", sa.String(128), nullable=False),
        sa.Column("value", _JSON, nullable=False),
        sa.Column("epistemic_label", sa.String(32), nullable=False),
        sa.Column("observation_date", sa.Date, nullable=True),
        sa.Column("retrieval_date", sa.Date, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "financial_data",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("metric_id", sa.String(64), nullable=False),
        sa.Column("period_end_date", sa.Date, nullable=False),
        sa.Column("value", sa.Numeric(24, 6), nullable=True),
        sa.Column("epistemic_label", sa.String(32), nullable=False),
        sa.Column("calculation_version", sa.String(32), nullable=True),
        sa.Column(
            "source_document_id", sa.Integer, sa.ForeignKey("source_documents.id"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("provider_name", sa.String(64), nullable=False),
        sa.Column("as_of_date", sa.Date, nullable=False),
        sa.Column("open", sa.Numeric(18, 6), nullable=False),
        sa.Column("high", sa.Numeric(18, 6), nullable=False),
        sa.Column("low", sa.Numeric(18, 6), nullable=False),
        sa.Column("close", sa.Numeric(18, 6), nullable=False),
        sa.Column("volume", sa.BigInteger, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "events",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("kind", sa.String(64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column(
            "source_document_id", sa.Integer, sa.ForeignKey("source_documents.id"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("claim_text", sa.Text, nullable=False),
        sa.Column("epistemic_label", sa.String(32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("claim_id", sa.Integer, sa.ForeignKey("claims.id"), nullable=False),
        sa.Column(
            "source_document_id", sa.Integer, sa.ForeignKey("source_documents.id"), nullable=True
        ),
        sa.Column("confidence", sa.Float, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "research",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("answer", sa.Text, nullable=False),
        sa.Column("epistemic_label", sa.String(32), nullable=False),
        sa.Column("tier", sa.String(16), nullable=False),
        sa.Column("provider_name", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("confidence", sa.Float, nullable=True),
        sa.Column("input_tokens", sa.Integer, nullable=True),
        sa.Column("output_tokens", sa.Integer, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "theses",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("evidence_ids", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("thesis_id", sa.Integer, sa.ForeignKey("theses.id"), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("epistemic_label", sa.String(32), nullable=False),
        sa.Column("assumptions", _JSON, nullable=False),
        sa.Column("catalysts", _JSON, nullable=False),
        sa.Column("risks", _JSON, nullable=False),
        sa.Column("unknowns", _JSON, nullable=False),
        sa.Column("invalidation_conditions", _JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("statement", sa.Text, nullable=False),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolves_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "outcomes",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("prediction_id", sa.Integer, sa.ForeignKey("predictions.id"), nullable=False),
        sa.Column("actual_result", sa.Text, nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("entity_id", sa.String(64), sa.ForeignKey("entities.entity_id"), nullable=False),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("rationale", sa.Text, nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supporting_thesis_id", sa.Integer, sa.ForeignKey("theses.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "provider_calls",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("provider_type", sa.String(32), nullable=False),
        sa.Column("provider_name", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("operation", sa.String(128), nullable=False),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_tokens", sa.Integer, nullable=True),
        sa.Column("output_tokens", sa.Integer, nullable=True),
        sa.Column("cost_usd", sa.Numeric(10, 4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("provider_calls")
    op.drop_table("decisions")
    op.drop_table("alerts")
    op.drop_table("outcomes")
    op.drop_table("predictions")
    op.drop_table("scenarios")
    op.drop_table("theses")
    op.drop_table("research")
    op.drop_table("evidence")
    op.drop_table("claims")
    op.drop_table("events")
    op.drop_table("market_data")
    op.drop_table("financial_data")
    op.drop_table("observations")
    op.drop_table("source_documents")
    op.drop_table("entities")
